### PR TITLE
Avoid table reload with CacheThenNetwork policy

### PR DESCRIPTION
**Pull request by gperks**
The block in findObjectsInBackgroundWithBlock is invoked twice; once
with results from the cache, and again with network results. This can
result in table reload & flicker even if the cache & network gave
identical results. Now a check between results is made and if
identical, we only load the table once.

### CODE REVIEW

**Comment by nlutsenko-fb** [comment]
This is a great idea, but I think it won't handle the pretty common scenario where the list of objects is the same, but data inside of them is different in cache vs fetched.

What do you think?

**Comment by gperks** [comment]
I think you're right; good point. It needs to be a deep object check for it to work correctly.

**Comment by facebook-github-bot-1** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by nlutsenko-fb** [comment]
Closing this for now, @gperks feel free to reopen at any time.

**Pull request closed without merging**
