### PR TITLE
🇧🇷 Adds Portuguese (BR) translation 🇧🇷

### PR DESCRIPTION
**Pull request by natanrolnik**

### CODE REVIEW

**Comment by natanrolnik** [comment]
Don't forget us, we want to be merged \o/

**Comment by natanrolnik** [comment]
@nlutsenko YOLO here as well :smile:

**Comment by nlutsenko** [comment]
surewhynot. YOLO!

**Comment by nlutsenko** [comment]
Oh, wait... Not yet :) Could you squash(fixup) both commits together?

**Comment by natanrolnik** [comment]
Yay @nlutsenko
I hope I did it right 🙃

**Comment by nlutsenko** [comment]
Yup, it's perfect now. Thanks!

**Pull request merged**
