### PR TITLE
Add loadInBackground:progressBlock: method to PFImageView.

### PR DESCRIPTION
**Pull request by kostub**

### CODE REVIEW

**Comment by nlutsenko-fb** [comment]
Hey @kostub, thanks for the PR!
Left some notes on code that are I think are necessary before we merge it in.

**Comment by kostub** [comment]
Made the changes.

**Comment by nlutsenko-fb** [comment]
Looks great! Thank you for fixing those nits.
Squash the commits into one and I will merge it in.

**Comment by nlutsenko-fb** [comment]
Superseded by #37

**Pull request closed without merging**
