### PR TITLE
🇫🇷 Add french localization of ParseUI.strings 🇫🇷

### PR DESCRIPTION
**Pull request by huguesbr**

### CODE REVIEW

**Comment by huguesbr** [comment]
@nlutsenko any change you can accept so I don't have to do weird hack anymore?

**Comment by huguesbr** [comment]
@natanrolnik thx for the flag idea ? :tongue:

**Comment by natanrolnik** [comment]
Trés bien, @huguesbr !
What is your "ugly hack"? Changing the pod URL in your podfile?

**Comment by huguesbr** [comment]
@natanrolnik https://github.com/ParsePlatform/ParseUI-iOS/issues/192

**Comment by natanrolnik** [comment]
Don't forget us, we want to be merged \o/

**Comment by huguesbr** [comment]
@nlutsenko yes could you merge this?

**Comment by huguesbr** [comment]
@nlutsenko  please?

**Comment by nlutsenko** [comment]
I have no idea whether it's accurate, but YOLO!

**Comment by huguesbr** [comment]
@nlutsenko awesome, thx! I swear it is ^^

**Pull request merged**
