### PR TITLE
Define PFLocalizedString, avoiding re-mapping NSLocalizedString macro.

### PR DESCRIPTION
**Pull request by huguesbr**

### CODE REVIEW

**Comment by nlutsenko** [comment]
Awesome! Will merge in after CLA is signed and Travis passes.

**Comment by nlutsenko** [comment]
Ok, great. Travis passed, the last piece is CLA - please sign it, so I can merge it in.

**Comment by huguesbr** [comment]
@nlutsenko for my education what is CLA?

**Comment by huguesbr** [comment]
@nlutsenko CLA done.. I hope I didn't just offer my very first born (or second, I already have a daughter...)

**Pull request merged**
