### PR TITLE
Adding spanish translations

### PR DESCRIPTION
**Pull request by estemendoza**
Adding spanish to ParseUI. I am a long time translator of subtitles for argenteam.net website. My username is the same as my github account if you want to check. Would be glad to answer any question.

### CODE REVIEW

**Comment by Casporro** [comment]
This translation is Latin Spanish, should be the standard/International Spanish

**Comment by estemendoza** [comment]
Thanks for the comment, but what strings do you consider are not "international spanish"?

**Comment by Casporro** [comment]
In this line for example:
```
"The email '%@' is taken. Please try using a different email." = "El correo '%@' ya está tomado. Por favor, usa un correo diferente.";
```
El correo '%@' ya está **usado o utilizado**. Por favor, usa un correo diferente.

In other lines the same happens.

**Comment by estemendoza** [comment]
Thanks, I will change it and make a new PR. Any other string that you consider that could be wrong?

**Comment by Casporro** [comment]
Sorry @estemendoza but I don't have more free time.
This are only suggestions:
```
/* Invalid login credentials alert message in PFLogInViewController */
"The username and password you entered don't match" = "El nombre de usuario y la contraseña introducidos no coinciden";
```
```
/* Username taken error format in PFSignUpViewController */
"The username '%@' is taken. Please try choosing a different username." = "El nombre de usuario '%@' ya está usado. Por favor, elije otro nombre de usuario.";
```
```
/* Invalid email address error message in PFSignUpViewControllers */
"The email address is invalid. Please enter a valid email." = "La dirección de correo es incorrecta. Por favor, introduce una dirección de correo válida.";
```
```
/* Sign Up Error */
"Sign Up Error" = "Error en el registro";
```
```
/* Forgot password request title in PFLogInViewController */
"Reset Password" = "Reestablecimiento de contraseña";
```
```
/* Email request message in PFLogInViewController */
"Please enter the email address for your account." = "Por favor, introduce el correo electrónico para tu cuenta.";
```
```
/* Password missing error message in PFSignUpViewController */
"Please enter a password." = "Por favor, introduce una contraseña.";

/* Username missing error message in PFSignUpViewController */
"Please enter a username." = "Por favor, introduce un nombre de usuario.";

/* Email missing error message in PFSignUpViewController */
"Please enter an email." = "Por favor, introduce un correo electrónico.";
```
```
/* Password reset error alert title in PFLogInViewController. */
"Password Reset Failed" = "El reestablecimiento de la contraseña falló";
```
```
/* Log In with Facebook */
"Log In with Facebook" = "Inicia sesión con Facebook";

/* Log In with Twitter */
"Log In with Twitter" = "Inicia sesión con Twitter";
```
```
/* Password reset message in PFLogInViewController */
"An email with reset instructions has been sent to '%@'." = "Se envió un correo con instrucciones para reestablecer la contraseña a '%@'.";
```

**Pull request closed without merging**
