### PR TITLE
Fix Podfile for CocoaPods-1.0

### PR DESCRIPTION
**Pull request by thiagoghisi**
`exclusive=>true` flag for targets was deprecated on cocoapods 1.0 release

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by nlutsenko** [comment]
Thank you! Will merge in as soon as CLA is signed!

**Comment by thiagoghisi** [comment]
@nlutsenko Fixing the build right now... I think I will also create a pull request to add instructions on how to run the project tests on the README.

**Comment by facebook-github-bot-4** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by thiagoghisi** [comment]
@nlutsenko giving up for today. It is a problem while importing Facebook SDK:

http://stackoverflow.com/questions/29435377/facebook-ios8-sdk-build-module-error-for-fbsdkcorekit/29457503#29457503

Unfortunately, all the solutions that I found are for people that had installed the Facebook SDK manually, not via cocoapods. It also looks like a bug on Facebook iOS SDK that is marked as solved, but a bunch of people are still complaining: https://developers.facebook.com/bugs/362995353893156/#_=_

**Comment by thiagoghisi** [comment]
FYI, removing the `use_frameworks!` line out of the Podfile make the test pass for the Objective-C build, but it still fail for the ParseUIDemo-Swift build.

**Comment by thiagoghisi** [comment]
@nlutsenko I finally took the time to fix the build. All green now. Let me know if you have any questions.

**Comment by thiagoghisi** [comment]
@nlutsenko let me know if you have any question here. The build is fixed now.

**Comment by davemurphysf** [comment]
@nlutsenko can we merge this in? waiting on this dependency to upgrade CocoaPods to 1.0

**Comment by nlutsenko** [comment]
All done. Sorry for delay. Glad we have this fixed.

**Pull request merged**
