### PR TITLE
Spelling

### PR DESCRIPTION
**Pull request by hhanesand**
Defualt -> Default

### CODE REVIEW

**Comment by nlutsenko** [comment]
Nice. Thanks for catching this!
Will merge in after Travis passes, since it's a required check.

**Comment by hhanesand** [comment]
It's also in the `PFQueryCollectionViewController`, one sec

**Comment by nlutsenko** [comment]
Great! Can you squash 2 commits together?

**Comment by hhanesand** [comment]
How would I best achieve that? (rebase?) Not too familiar with git

**Comment by nlutsenko** [comment]
-  `git rebase -i origin/master`
-  In text editor that opened - you should see 2 lines starting with `pick` and followed by commit hash + message.
- Simply change second line to start from `f` or `fixup`
- Close the text editor saving the changes
- `git push -f`
- ???
- Profit

**Comment by hhanesand** [comment]
Ok, got it, I had to configure sublime as the default git editor. Thanks for the help :+1: 

About the CLA, I've already submitted one, but I've changed my username lately, so I'm waiting for them to update it.

**Comment by nlutsenko** [comment]
Sure, once the bot confirms the CLA signed - will merge in.

**Comment by nlutsenko** [comment]
@hhanesand I suggest you try re-accepting the CLA, or I won't be able to merge it in...

**Comment by hhanesand** [comment]
Ok, I accepted it again with a different email

**Comment by nlutsenko** [comment]
Great. Merging in now.

**Pull request merged**
